inherit: true
environment:
  PATH:
    - <inherit>
    - <scoop>/apps/scoop/current/bin
    - <scoop>/apps/starship/current
    - C:/Windows
    - C:/Windows/System32
    - C:/Windows/System32/OpenSSH
    - C:/Windows/System32/Wbem
