alias:
  pc: <home>/apps/jetbrains-toolbox/scripts/pycharm
  py: <home>/apps/python/3.12/python.exe
  pip: <py> -m pip
  po: <py> -m poetry
  pob: <po> build -f wheel
  poe: <po> env info
  por: <po> run
  pou: <po> update
  pox: <po> run python
  st: <por> streamlit
  strun: <por> streamlit run --server.headless true --server.port
environment:
  NODE_PATH: <home>/apps/nodejs/global_modules/node_modules
  PATH:
    - <home>/apps/git/cmd
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nushell
    - <home>/apps/python/3.12
    - <home>/apps/python/3.12/scripts
    - <home>/apps/vscode/bin
  PNPM_HOME: <home>/apps/nodejs/pnpm
  PYTHONPATH:
    - .
    - src
    - lib
