alias:
  pc: <home>/apps/jetbrains-toolbox/scripts/pycharm
  py: <home>/apps/python/3.12/python.exe
  pip: <py> -m pip
  po: <py> -m poetry
  pob: <po> build -f wheel
  poe: <po> env info
  poi: <po> install --no-root
  por: <po> run
  pou: <po> update
  pox: <po> run python
  st: <por> streamlit
  strun: <por> streamlit run --browser.gatherUsageStats false --server.headless true --server.port
environment:
  HTTP_PROXY: http://127.0.0.1:7890
  HTTPS_PROXY: http://127.0.0.1:7890
  PATH:
    - <home>/apps/alist
    - <home>/apps/dufs
    - <home>/apps/git/bin
    - <home>/apps/java/jdk-22.0/bin
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nodejs/22.2
    - <home>/apps/nushell
    - <home>/apps/vscode/bin
  PYTHONPATH:
    - .
    - src
    - lib
  PYTHONUTF8: 1
