inherit: map.yaml
environment:
  PATH:
    - <inherit>
    - <user_home>/scoop/shims
    - C:/Windows
    - C:/Windows/System32
    - C:/Windows/System32/OpenSSH
    - C:/Windows/System32/Wbem
    - C:/Windows/System32/WindowsPowerShell/v1.0
