inherit: map.yaml
environment:
  PATH:
    - <home>/apps/alist
    - <home>/apps/bore
    - <home>/apps/caddy
    - <home>/apps/code-server/bin
    - <home>/apps/flutter/3.7/bin
    - <home>/apps/git/cmd
    - <home>/apps/go/1.20/bin
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nodejs/20.3/bin
    - <home>/apps/nodejs/global_modules
    - <home>/apps/nodejs/pnpm
    - <home>/apps/nushell
    - <home>/apps/python/3.12/bin
    - <home>/apps/vscode/bin
    - /Users/Likianta/.bun/bin
    - /Users/Likianta/.cargo/bin
    - /usr/local/bin
    - /usr/local/sbin
    - /usr/bin
    - /usr/sbin
    - /bin
