inherit: map.yaml
environment:
  NODE_PATH: <home>/apps/nodejs/global_modules/node_modules
  PATH:
    - <home>/apps/alist
    - <home>/apps/bore
    - <home>/apps/caddy
    - <home>/apps/flutter/3.7/bin
    - <home>/apps/git/cmd
    - <home>/apps/go/1.20/bin
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nodejs/20.3/bin
    - <home>/apps/nodejs/global_modules
    - <home>/apps/nodejs/pnpm
    - <home>/apps/nushell
    - <home>/apps/python/3.12
    - <home>/apps/python/3.12/scripts
    - <home>/apps/vscode/bin
    - <user_home>/scoop/shims
  PNPM_HOME: <home>/apps/nodejs/pnpm
  PYTHONPATH:
    - .
    - src
    - lib
