inherit: map.yaml
home: C:/Likianta
map:
  <inherit>: ...
  <home>/apps/scoop/apps: <shortcut>/scoop-apps
  <home>/apps/scoop/shims: <shortcut>/scoop-shims
  <home>/pictures/收集: <shortcut>/pictures-inbox
  <home>/pictures/收集/<yyyy>: <shortcut>/pictures-inbox-(<yyyy>)
  <home>/workspace/com_jlsemi_likianta: <shortcut>/likianta.jlsemi.com
  <home>/workspace/dev_master_likianta: <shortcut>/likianta.master.dev
