from argsense import cli
from lk_utils import dumps
from lk_utils import fs
from lk_utils import timestamp

from mypc_settings import common


@cli.cmd()
def main(
    output_file: str = 'C:/Users/Likianta/Documents/WindowsPowerShell/Microsoft'
                       '.PowerShell_profile.ps1',
    turn_to_nushell: bool = False,
) -> None:
    cfg = common.loads_config(fs.xpath('../config/shell/config.yaml'))
    output = [
        '# this file is auto generated by [prj] '
        'personalized-computer-settings : mypc_settings/'
        'make_powershell_profile.py',
        '# file was updated at {}'.format(timestamp('y-m-d h:m:s')),
        '',
        'oh-my-posh init pwsh --config $env:POSH_THEMES_PATH\\amro.omp.json | '
        'Invoke-Expression',
        '',
    ]
    
    # env vars
    for key, val in cfg['environment'].items():
        output.append('Set-Item -Path env:{} -Value "{}"'.format(
            key, ';'.join(val)
        ))
    output.append('')
    
    # alias
    for key, val in cfg['alias'].items():
        common.print_conversion(key, val)
        # output.append('New-Alias -Name {} -Value "{}"'.format(key, val))
        output.append('function {} {{ {} $args }}'.format(key, val))
        #   https://stackoverflow.com/a/4167071
    output.append('')
    
    if turn_to_nushell:
        output.append('C:/Likianta/apps/nushell/nu.exe')
    
    dumps(output, output_file, 'plain')


if __name__ == '__main__':
    # pox mypc_settings/make_powershell_profile.py
    cli.run(main)
