[tool.poetry]
name = "mypc-settings"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
# readme = "README.md"
packages = [{ include = "mypc_settings" }]

[tool.poetry.dependencies]
python = "^3.12"
argsense = "^0.5.8"
ipython = "^8.23.0"
lk-logger = { version = "^6.0.0a26", source = "likianta-host" }
lk-utils = { version = "^3.0.0b5", source = "likianta-host" }
psutil = "*"
pywin32 = "*"
streamlit = "^1.39.0"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
