[tool.poetry]
name = "mypc-settings"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
# readme = "README.md"
packages = [{ include = "mypc_settings" }]

[tool.poetry.dependencies]
python = "^3.12"
argsense = { version = "^0.6.4a1", source = "likianta-host" }
ipython = "^8.23.0"
lk-logger = { version = "^6.0.3", source = "likianta-host" }
lk-utils = { version = "^3.1.3a1", source = "likianta-host" }
psutil = "^6.1.1"
pywin32 = { version = "^308", platform = "win32" }
streamlit = "^1.41.0"

pyarrow = "^18.1.0"  # <- streamlit

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta-host"
url = "http://likianta.pro:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
