[tool.poetry]
name = "mypc-settings"
version = "0.1.0"
description = ""
authors = ["likianta <likianta@foxmail.com>"]
# readme = "README.md"
packages = [{ include = "mypc_settings" }]

[tool.poetry.dependencies]
python = "^3.12"
argsense = { version = "^0.7.1", source = "likianta" }
ipython = "^9.0.0"
lk-logger = { version = "^6.0.5", source = "likianta" }
lk-utils = { version = "^3.1.3", source = "likianta" }
psutil = "^6.1.1"
pywin32 = { version = "^308", platform = "win32" }
streamlit = "^1.43.0"

# pyarrow = "^18.1.0"  # <- streamlit
# rpds-py = "^0.22.3"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[[tool.poetry.source]]
name = "likianta"
url = "http://47.102.108.149:2131/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
