- name: alist server
  cmd: <likianta>/apps/alist/alist.exe server
  cwd: <likianta>/apps/alist
# - name: dev dist publisher
#   cmd: <strun> 2130 src/dev_dist/app.py
#   cwd: <likianta>/workspace/dev.master.likianta/likianta-domain
- name: file sync pro
  cmd: <strun> 2163 src/file_sync_pro/ui/main.py 172.20.128.101
  cwd: <likianta>/workspace/dev.master.likianta/file-sync-pro
- name: gitbook online editor
  cmd:
    - <strun> 2160 crossplatform_editor/app.py
    - <bore> -p 2160 2160
  cwd: <likianta>/documents/gitbook/scripts
# - name: gitbook online editor
#   cmd:
#     - <por> jupyter notebook --no-browser --ip 0.0.0.0 --port 2161 ..
#     - <bore> -p 2161 2161
#   cwd: <likianta>/documents/gitbook/scripts
- name: intranet messenging
  cmd: <strun> 2017 projects/intranet_messenging/ui.py
  cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: latest package on pypi
  cmd: <strun> 2013 projects/latest_package_on_pypi/app_st.py
  cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: make symlink
  cmd: <strun> 2009 projects/mklink_gui/app.py
  cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: markdown image base64
  cmd: <strun> 2165 src/markdown_image_base64/md_img_b64/ui.py
  cwd: <likianta>/workspace/dev.master.likianta/markdown-toolset
- name: markdown image paste
  cmd: <strun> 2164 src/markdown_image_paste/md_img_paste/app_st.py
  cwd: <likianta>/workspace/dev.master.likianta/markdown-toolset
# - name: ora cat car energy estimation
#   cmd:
#     - <strun> 2020 projects/ora_car_energy_statistics/ui2.py
#     - <bore> -p 2020 2020
#   cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: poetry extension
  cmd: <strun> 2016 projects/poetry_extensions/help_me_explain_poetry_error.py
  cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: rtmp server
  cmd: 
    - <pox> projects/rtmp_server/server.py
    - <bore> -p 2014 2014
  cwd: <likianta>/workspace/dev.master.likianta/mini-toolbox
- name: rust desk (2170 -> 2171)
  cmd: <bore> -p 2171 2170
- name: rust desk (2170 -> 2172)
  cmd: <bore> -p 2172 2170
- name: self-hosted pypi (localnet)
  cmd:
    - <strun> 2190 src/dev_dist/app.py
    - <python> -m http.server 2191 -d data/dev_dist
    - dufs -A -p 2192 data/dev_dist
    - <python> -m http.server 2193 -d data/reqlock
- name: self-hosted pypi (public)
  cmd:
    - <bore> -p 2191 2191
    - <bore> -p 2192 2192
    - <bore> -p 2193 2193
- name: temp share anything (localhost)
  cmd: dufs -A -p 2019 <likianta>/temp/2026-03
- name: temp share to public
  cmd: <bore> -p 2019 2019
- name: teslamate
  cmd:
    # - <bore> -p 2003 2003
    - <bore> -p 2004 2004
