home: C:/Likianta
map:
  applist: ...
  apps: ...
  apps/python/3.12: shortcut/python-3.12
  apps/pypoetry/cache/virtualenvs: shortcut/pypoetry-env
  backups: ...
  backups/software-packages: ...
  backups/software-settings: ...
  documents: ...
  documents/appdata: ...
  documents/gitbook-ssg: shortcut/gitbook
  downloads: ...
  pictures: ...
  pictures/收集: shortcut/pictures-inbox
  pictures/收集/<yyyy>: shortcut/pictures-inbox-(<yyyy>)
  temp: ...
  temp/<yyyy>-<mm>: shortcut/temp-(<yyyy>-<mm>)
  workspace: ...
  workspace/com_jlsemi_likianta: shortcut/likianta.jlsemi.com
  workspace/dev_master_likianta: shortcut/likianta.master.dev
  workspace/playground/python-playground: ...
