home: C:/Likianta
alias:
  pc: <home>/apps/jetbrains-toolbox/scripts/pycharm
  py: <home>/apps/python/3.13/python.exe
  # ---
  ipython: <py> -m IPython
  pip: <py> -m pip
  po: <py> -m poetry
  pob: <po> build -f wheel
  poe: <po> env info
  poi: <po> install --no-root
  por: <po> run
  pou: <po> update
  pox: <po> run python
  # ---
  strun: <por> streamlit run --browser.gatherUsageStats false --runner.magicEnabled false --server.headless true --server.port
environment:
  HTTP_PROXY: http://127.0.0.1:7890
  HTTPS_PROXY: http://127.0.0.1:7890
  PATH:
    - <home>/apps/bore
    - <home>/apps/dufs
    - <home>/apps/git/bin
    - <home>/apps/java/jdk-22.0/bin
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nushell
    - <home>/apps/python/3.13
    - <home>/apps/python/3.13/Scripts
    - <home>/apps/scoop/apps/flutter/current/bin
    - <home>/apps/scoop/apps/pnpm/current
    - <home>/apps/scoop/shims
    - <home>/apps/visual-studio-code/bin
    # - C:/Program Files/PowerShell/7
    - C:/Windows/System32/WindowsPowerShell/v1.0
  PNPM_HOME: <home>/apps/scoop/apps/pnpm/current
  PYTHONPATH:
    - .
    - src
    - lib
  PYTHONUTF8: 1
shortcut:
  <home>/applist: <shortcut>/<name_as_is>
  <home>/apps: <shortcut>/<name_as_is>
  <home>/apps/python/3.13: <shortcut>/python-3.13
  <home>/apps/pypoetry/cache/virtualenvs: <shortcut>/pypoetry-env
  <home>/apps/scoop/apps: <shortcut>/scoop-apps
  <home>/apps/scoop/shims: <shortcut>/scoop-shims
  <home>/backups: <shortcut>/<name_as_is>
  <home>/backups/software-packages: <shortcut>/<name_as_is>
  <home>/backups/software-settings: <shortcut>/<name_as_is>
  <home>/documents: <shortcut>/<name_as_is>
  <home>/documents/appdata: <shortcut>/<name_as_is>
  <home>/documents/gitbook-ssg/source-docs: <shortcut>/gitbook
  <home>/downloads: <shortcut>/<name_as_is>
  <home>/pictures: <shortcut>/<name_as_is>
  <home>/temp: <shortcut>/<name_as_is>
  <home>/temp/<yyyy>-<mm>: <shortcut>/temp-(<yyyy>-<mm>)
  <home>/workspace: <shortcut>/<name_as_is>
  <home>/workspace/com.jlsemi.likianta: <shortcut>/com.jlsemi.likianta
  <home>/workspace/dev.master.likianta: <shortcut>/dev.master.likianta
  <home>/workspace/playground/python-playground: <shortcut>/<name_as_is>
  C:/Users/Likianta: <shortcut>/user.home.likianta
