home: C:/Likianta
alias:
  pc: <home>/apps/jetbrains-toolbox/scripts/pycharm
  po: <home>/apps/python/3.13/Scripts/poetry.exe
  py: <home>/apps/python/3.13/python.exe
  py38: <home>/apps/python/3.8/python.exe
  py39: <home>/apps/python/3.9/python.exe
  py310: <home>/apps/python/3.10/python.exe
  py311: <home>/apps/python/3.11/python.exe
  py312: <home>/apps/python/3.12/python.exe
  uvr: uv run --no-sync --frozen --all-groups
  uvs: uv sync --no-install-project --all-groups
  uvx: uv run --no-sync --frozen --all-groups python
  # ---
  ipython: <py> -m IPython
  pip: <py> -m pip
  pip38: <py38> -m pip
  pip39: <py39> -m pip
  pip310: <py310> -m pip
  pip311: <py311> -m pip
  pip312: <py312> -m pip
  pob: <po> build -f wheel
  poe: <po> env info
  poi: <po> install --no-root
  por: <po> run
  pou: <po> update
  pox: <po> run python
  # ---
  strun: <por> streamlit run --browser.gatherUsageStats false --runner.magicEnabled false --server.headless true --server.port
environment:
  # FLUTTER_STORAGE_BASE_URL: https://storage.flutter-io.cn
  HTTP_PROXY: http://127.0.0.1:7890
  HTTPS_PROXY: http://127.0.0.1:7890
  NO_PROXY: localhost,127.0.0.1,192.168.*,::1
  PATH:
    - <home>/apps/bore
    - <home>/apps/dufs
    - <home>/apps/flutter/bin
    - <home>/apps/git/bin
    - <home>/apps/java/jdk-22.0/bin
    - <home>/apps/jetbrains-toolbox/scripts
    - <home>/apps/nushell
    - <home>/apps/python/3.13
    - <home>/apps/python/3.13/Scripts
    - <home>/apps/scoop/apps/pnpm/current
    - <home>/apps/scoop/shims
    - <home>/apps/vscode/bin
    # - C:/Program Files/PowerShell/7
    - C:/Windows/System32/WindowsPowerShell/v1.0
  PNPM_HOME: <home>/apps/scoop/apps/pnpm/current
  PUB_CACHE: <home>/documents/appdata/flutter/pub-cache
  # PUB_HOSTED_URL: https://pub.flutter-io.cn
  PYTHONPATH:
    - .
    - src
    - lib
  PYTHONUTF8: 1
shortcut:
  <home>/applist: <shortcut>/<name_as_is>
  <home>/apps: <shortcut>/<name_as_is>
  <home>/apps/python/3.13: <shortcut>/python-3.13
  <home>/apps/pypoetry/cache/virtualenvs: <shortcut>/pypoetry-env
  <home>/apps/scoop/apps: <shortcut>/scoop-apps
  <home>/apps/scoop/shims: <shortcut>/scoop-shims
  <home>/backups: <shortcut>/<name_as_is>
  <home>/backups/software-packages: <shortcut>/<name_as_is>
  <home>/backups/software-settings: <shortcut>/<name_as_is>
  <home>/documents: <shortcut>/<name_as_is>
  <home>/documents/appdata: <shortcut>/<name_as_is>
  <home>/documents/gitbook/source-docs: <shortcut>/gitbook
  <home>/downloads: <shortcut>/<name_as_is>
  <home>/pictures: <shortcut>/<name_as_is>
  <home>/temp: <shortcut>/<name_as_is>
  <home>/temp/<yyyy>-<mm>: <shortcut>/temp-(<yyyy>-<mm>)
  <home>/workspace: <shortcut>/<name_as_is>
  <home>/workspace/com.jlsemi.likianta: <shortcut>/com.jlsemi.likianta
  <home>/workspace/dev.master.likianta: <shortcut>/dev.master.likianta
  <home>/workspace/playground/python-playground: <shortcut>/<name_as_is>
  C:/Users/Likianta: <shortcut>/user.home.likianta
