home: /home/likianta/Desktop
map:
  applist: ...
  apps: ...
  apps/python/3.12: shortcut/python-3.12
  apps/pypoetry/cache/virtualenvs: shortcut/pypoetry-env
  backups: ...
  backups/software-packages: ...
  backups/software-settings: ...
  documents: ...
  documents/appdata: ...
  documents/gitbook-ssg: shortcut/gitbook
  downloads: ...
  pictures: ...
  pictures/Inbox: shortcut/pictures-inbox
  pictures/Inbox/{yyyy}: shortcut/pictures-inbox-({yyyy})
  temp: ...
  temp/{yyyy}-{mm}: shortcut/temp-({yyyy}-{mm})
  workspace: ...
  workspace/com.jlsemi.likianta: shortcut/likianta.jlsemi.com
  workspace/dev.master.likianta: shortcut/likianta.master.dev
  workspace/playground/python-playground: ...
